### ISSUE TITLE
Refactor MVC Pattern

### ISSUE THREAD

**Issue by berazo29** [berazo29/randomApiAuth#33]
**Tasks**
- [ ] Controller and Models needs to be refactored to follow MVC pattern. 
- [ ] Create interfaces between modules for performing unit testing and reduce the number of integration test.
- [ ] Create a configuration folder where all modules related to it must be moved.
- [ ] Database tools must be moved to another location where it can be easily manage.
